linters:
  enable:
    - errcheck
    - staticcheck
linters-settings:
  errcheck:
    exclude-functions:
      - fmt.Fprint
      - fmt.Fprintf
      - fmt.Fprintln
      - (io.Closer).Close
      - (*os.File).Close
      - (net.Listener).Close
