version: "2"
linters:
  enable:
    - errcheck
    - staticcheck
  settings:
    errcheck:
      exclude-functions:
        - fmt.Fprint
        - fmt.Fprintf
        - fmt.Fprintln
        - (io.Closer).Close
        - (*os.File).Close
        - (net.Listener).Close
