version: 2

before:
  hooks:
    - go mod tidy

builds:
  - id: salja
    main: ./cmd/salja
    binary: salja
    env:
      - CGO_ENABLED=0
    goos:
      - darwin
      - linux
      - windows
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w
      - -X main.version={{.Version}}
      - -X main.commit={{.Commit}}
      - -X main.buildDate={{.Date}}
  - id: salja-mcp
    main: ./cmd/salja-mcp
    binary: salja-mcp
    env:
      - CGO_ENABLED=0
    goos:
      - darwin
      - linux
      - windows
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w
      - -X main.version={{.Version}}

archives:
  - format: tar.gz
    name_template: "{{ .ProjectName }}_{{ .Os }}_{{ .Arch }}"
    format_overrides:
      - goos: windows
        format: zip

checksum:
  name_template: "checksums.txt"

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"

brews:
  - name: salja
    repository:
      owner: gongahkia
      name: homebrew-salja
    homepage: "https://github.com/gongahkia/salja"
    description: "Universal calendar and task converter CLI"
    license: "MIT"
    test: |
      system "#{bin}/salja", "--version"
